In [2]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_csv(r"C:\Users\chyj2\OneDrive\Desktop\baltimore-crime-analytics\data\cleaned\cleaned_crime_data.csv")

C:\Users\chyj2\AppData\Local\Temp\ipykernel_8256\2856710531.py:4: DtypeWarning: Columns (5,7,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\chyj2\OneDrive\Desktop\baltimore-crime-analytics\data\cleaned\cleaned_crime_data.csv")

In [12]:
print(df.columns)

Index(['rowid', 'ccnumber', 'crimedatetime', 'crimecode', 'description',
       'inside_outside', 'weapon', 'post', 'gender', 'age', 'race',
       'ethnicity', 'location', 'old_district', 'new_district', 'neighborhood',
       'latitude', 'longitude', 'geolocation', 'premisetype',
       'total_incidents', 'x', 'y', 'year', 'month', 'month_name',
       'day_of_week'],
      dtype='object')

In [5]:
#Crime Type Analysis This step quickly counts how many times each specific 
#type of crime (e.g., Robbery, Larceny) appears in the entire dataset.
    # Count incidents by crime description
crime_type = df["description"].value_counts().reset_index()

# Rename the columns for clarity
crime_type.columns = ["crime_type", "total"]

crime_type.head()

          crime_type   total
0            LARCENY  143753
1     COMMON ASSAULT  118910
2           BURGLARY   83658
3  LARCENY FROM AUTO   79085
4       AGG. ASSAULT   74320

In [3]:
## Monthly crime Agregation
# Group data by year and month to get total monthly volume
monthly_crime = df.groupby(["year", "month"]).size().reset_index(name="total_crimes")

# View the first few rows to verify
monthly_crime.head()

     year  month  total_crimes
0  1900.0    5.0             1
1  1920.0    6.0             1
2  1922.0    6.0             1
3  1928.0    9.0             1
4  1930.0   10.0             1

In [13]:
# 1. Print the column names to see the exact spelling
print("Available columns:", df.columns.tolist())

# Drop rows with missing geographic coordinates
hotspots = df.dropna(subset=["latitude", "longitude"])

# 2. Update this list with the EXACT column names printed above
columns_to_keep = ["description", "new_district", "neighborhood", "latitude", "longitude", "crimedatetime"]

# Filter down to only the columns needed for the map
hotspots = hotspots[columns_to_keep]

# Save the cleaned data to a CSV file
hotsports.to_csv("outputs/tables/crime_hotspots.csv", index=False)

Available columns: ['rowid', 'ccnumber', 'crimedatetime', 'crimecode', 'description', 'inside_outside', 'weapon', 'post', 'gender', 'age', 'race', 'ethnicity', 'location', 'old_district', 'new_district', 'neighborhood', 'latitude', 'longitude', 'geolocation', 'premisetype', 'total_incidents', 'x', 'y', 'year', 'month', 'month_name', 'day_of_week']

NameError: name 'hotsports' is not defined